#!/usr/bin/env python3
"""
Analyze Box64 Dynarec Purge Log (tick-based age system)
Parses log files generated by BOX64_DYNAREC_PURGE_FILE
"""

import re
import sys
from collections import defaultdict, Counter
import argparse

def parse_purge_log(filename):
    """Parse purge log and extract structured data"""

    # Regex patterns matching our log format
    success_pattern = r'\[PURGE SUCCESS\] Purging old block (0x[0-9a-fA-F]+) \(x64_addr=(0x[0-9a-fA-F]+), last_used_tick=(\d+), current_age=(\d+), min_age_required=(\d+)\)'
    blocked_pattern = r'\[PURGE BLOCKED\] Can\'t purge block (0x[0-9a-fA-F]+) \(x64_addr=(0x[0-9a-fA-F]+), in_used=(\d+), last_used_tick=(\d+), current_age=(\d+), min_age_required=(\d+)\)'
    skip_pattern = r'\[PURGE SKIP\] Block too young (0x[0-9a-fA-F]+) \(x64_addr=(0x[0-9a-fA-F]+), in_used=(\d+), last_used_tick=(\d+), current_age=(\d+), min_age_required=(\d+)\)'

    events = []
    line_count = 0

    with open(filename, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            line_count += 1

            # Try PURGE SUCCESS
            match = re.search(success_pattern, line)
            if match:
                events.append({
                    'type': 'SUCCESS',
                    'line': line_num,
                    'dynablock': match.group(1),
                    'x64_addr': match.group(2),
                    'last_used_tick': int(match.group(3)),
                    'current_age': int(match.group(4)),
                    'min_age_required': int(match.group(5))
                })
                continue

            # Try PURGE BLOCKED
            match = re.search(blocked_pattern, line)
            if match:
                events.append({
                    'type': 'BLOCKED',
                    'line': line_num,
                    'dynablock': match.group(1),
                    'x64_addr': match.group(2),
                    'in_used': int(match.group(3)),
                    'last_used_tick': int(match.group(4)),
                    'current_age': int(match.group(5)),
                    'min_age_required': int(match.group(6))
                })
                continue

            # Try PURGE SKIP
            match = re.search(skip_pattern, line)
            if match:
                events.append({
                    'type': 'SKIP',
                    'line': line_num,
                    'dynablock': match.group(1),
                    'x64_addr': match.group(2),
                    'in_used': int(match.group(3)),
                    'last_used_tick': int(match.group(4)),
                    'current_age': int(match.group(5)),
                    'min_age_required': int(match.group(6))
                })
                continue

    return events, line_count

def analyze_events(events):
    """Perform statistical analysis on parsed events"""

    if not events:
        print("No purge events found in log file!")
        return

    # Basic counts
    type_counts = Counter(e['type'] for e in events)
    total = len(events)

    print("=" * 70)
    print("PURGE EVENT SUMMARY")
    print("=" * 70)
    print(f"Total events: {total:,}")
    print()
    print(f"  {'SUCCESS':<12} (purged):        {type_counts['SUCCESS']:>10,} ({100*type_counts['SUCCESS']/total:>5.1f}%)")
    print(f"  {'BLOCKED':<12} (in use):        {type_counts['BLOCKED']:>10,} ({100*type_counts['BLOCKED']/total:>5.1f}%)")
    print(f"  {'SKIP':<12} (too young):     {type_counts['SKIP']:>10,} ({100*type_counts['SKIP']/total:>5.1f}%)")
    print()

    # Purge efficiency
    eligible = type_counts['SUCCESS'] + type_counts['BLOCKED']
    if eligible > 0:
        success_rate = 100 * type_counts['SUCCESS'] / eligible
        print(f"Purge Success Rate: {success_rate:.1f}% (of age-eligible blocks)")
        print(f"  -> {type_counts['BLOCKED']:,} blocks were old enough but in use")
    print()

    # Age statistics
    print("=" * 70)
    print("AGE STATISTICS")
    print("=" * 70)

    # For SUCCESS events
    success_events = [e for e in events if e['type'] == 'SUCCESS']
    if success_events:
        ages = [e['current_age'] for e in success_events]
        print(f"Purged blocks (SUCCESS):")
        print(f"  Count:     {len(ages):,}")
        print(f"  Age range: {min(ages):,} - {max(ages):,}")
        print(f"  Avg age:   {sum(ages)/len(ages):,.1f}")
    print()

    # For SKIP events
    skip_events = [e for e in events if e['type'] == 'SKIP']
    if skip_events:
        ages = [e['current_age'] for e in skip_events]
        print(f"Skipped blocks (too young):")
        print(f"  Count:     {len(ages):,}")
        print(f"  Age range: {min(ages):,} - {max(ages):,}")
        print(f"  Avg age:   {sum(ages)/len(ages):,.1f}")
    print()

    # For BLOCKED events
    blocked_events = [e for e in events if e['type'] == 'BLOCKED']
    if blocked_events:
        ages = [e['current_age'] for e in blocked_events]
        in_used_vals = [e['in_used'] for e in blocked_events]
        print(f"Blocked blocks (in use):")
        print(f"  Count:     {len(ages):,}")
        print(f"  Age range: {min(ages):,} - {max(ages):,}")
        print(f"  Avg age:   {sum(ages)/len(ages):,.1f}")
        print()
        print(f"  In-use distribution:")
        in_used_dist = Counter(in_used_vals)
        for val in sorted(in_used_dist.keys())[:10]:
            print(f"    in_used={val}: {in_used_dist[val]:,}")
    print()

    # Age distribution overview
    print("=" * 70)
    print("AGE DISTRIBUTION (all events)")
    print("=" * 70)

    all_ages = [e['current_age'] for e in events]
    age_ranges = [
        (0, 100, "0-100"),
        (100, 500, "100-500"),
        (500, 1000, "500-1K"),
        (1000, 2000, "1K-2K"),
        (2000, 5000, "2K-5K"),
        (5000, 10000, "5K-10K"),
        (10000, 50000, "10K-50K"),
        (50000, float('inf'), "50K+")
    ]

    for low, high, label in age_ranges:
        count = sum(1 for a in all_ages if low <= a < high)
        if count > 0:
            pct = 100 * count / len(all_ages)
            # Break down by type
            success_cnt = sum(1 for e in events if e['type'] == 'SUCCESS' and low <= e['current_age'] < high)
            blocked_cnt = sum(1 for e in events if e['type'] == 'BLOCKED' and low <= e['current_age'] < high)
            skip_cnt = sum(1 for e in events if e['type'] == 'SKIP' and low <= e['current_age'] < high)
            print(f"  {label:>10}: {count:>10,} ({pct:>5.1f}%)  [S:{success_cnt:,} B:{blocked_cnt:,} K:{skip_cnt:,}]")
    print()

    # Unique address analysis
    print("=" * 70)
    print("UNIQUE ADDRESS SUMMARY (by x64 address)")
    print("=" * 70)

    # Get unique x64 addresses per event type
    success_x64 = set(e['x64_addr'] for e in events if e['type'] == 'SUCCESS')
    blocked_x64 = set(e['x64_addr'] for e in events if e['type'] == 'BLOCKED')
    skip_x64 = set(e['x64_addr'] for e in events if e['type'] == 'SKIP')

    all_x64 = success_x64 | blocked_x64 | skip_x64
    unique_dynablocks = len(set(e['dynablock'] for e in events))

    print(f"Unique dynablock pointers: {unique_dynablocks:,}")
    print(f"Unique x64 addresses:      {len(all_x64):,}")
    print()
    print(f"  {'SUCCESS':<12} (purged):        {len(success_x64):>10,} unique x64 addresses")
    print(f"  {'BLOCKED':<12} (in use):        {len(blocked_x64):>10,} unique x64 addresses")
    print(f"  {'SKIP':<12} (too young):     {len(skip_x64):>10,} unique x64 addresses")
    print()

    # Recreation analysis
    recreated_x64 = success_x64 & skip_x64
    print(f"X64 addresses purged AND later skipped (recreated): {len(recreated_x64):,}")

    only_purged = success_x64 - skip_x64 - blocked_x64
    print(f"X64 addresses only purged (clean purge):            {len(only_purged):,}")

    only_skipped = skip_x64 - success_x64 - blocked_x64
    print(f"X64 addresses only skipped (always young):          {len(only_skipped):,}")

    only_blocked = blocked_x64 - success_x64 - skip_x64
    print(f"X64 addresses only blocked (always in use):         {len(only_blocked):,}")
    print()

def timeline_analysis(events, window_size=1000):
    """Analyze purging behavior over time"""

    if len(events) < window_size:
        print(f"Not enough events for timeline analysis (need at least {window_size})")
        return

    print("=" * 70)
    print(f"TIMELINE ANALYSIS (window size: {window_size})")
    print("=" * 70)

    print(f"{'Window':>10} | {'Total':>8} | {'Success':>8} | {'Blocked':>8} | {'Skip':>8} | {'S-Rate':>7}")
    print("-" * 70)

    step = window_size // 2
    for i in range(0, len(events) - window_size + 1, step):
        window = events[i:i+window_size]
        type_counts = Counter(e['type'] for e in window)

        eligible = type_counts['SUCCESS'] + type_counts['BLOCKED']
        success_rate = 100 * type_counts['SUCCESS'] / eligible if eligible > 0 else 0

        print(f"{i:>10} | {len(window):>8} | {type_counts['SUCCESS']:>8} | "
              f"{type_counts['BLOCKED']:>8} | {type_counts['SKIP']:>8} | {success_rate:>6.1f}%")
    print()

def export_csv(events, output_file):
    """Export events to CSV"""
    import csv

    with open(output_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Line', 'Type', 'Dynablock', 'X64_Addr', 'In_Used', 'Last_Used_Tick', 'Current_Age', 'Min_Age_Required'])

        for e in events:
            writer.writerow([
                e['line'],
                e['type'],
                e['dynablock'],
                e.get('x64_addr', ''),
                e.get('in_used', ''),
                e.get('last_used_tick', ''),
                e.get('current_age', ''),
                e.get('min_age_required', '')
            ])

    print(f"CSV exported to: {output_file}")

def main():
    parser = argparse.ArgumentParser(
        description='Analyze Box64 dynarec purge log (tick-based age system)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic analysis
  python3 analyze_purge_log.py /tmp/box64_purge_12345.log

  # With timeline analysis
  python3 analyze_purge_log.py purge.log --timeline

  # Export to CSV
  python3 analyze_purge_log.py purge.log --csv report.csv

  # Full analysis
  python3 analyze_purge_log.py purge.log --timeline --csv report.csv
        """
    )

    parser.add_argument('logfile', help='Path to the purge log file')
    parser.add_argument('--csv', metavar='FILE', help='Export to CSV file')
    parser.add_argument('--timeline', action='store_true', help='Show timeline analysis')
    parser.add_argument('--window', type=int, default=1000, help='Window size for timeline (default: 1000)')

    args = parser.parse_args()

    print(f"Parsing log file: {args.logfile}")
    events, line_count = parse_purge_log(args.logfile)
    print(f"Read {line_count:,} lines, found {len(events):,} purge events\n")

    if not events:
        print("No events found. Make sure the log contains purge messages.")
        print("Expected format:")
        print("  [PURGE SUCCESS] Purging old block 0x... (x64_addr=0x..., last_used_tick=..., current_age=..., min_age_required=...)")
        print("  [PURGE BLOCKED] Can't purge block 0x... (in_used=..., last_used_tick=..., current_age=..., min_age_required=...)")
        print("  [PURGE SKIP] Block too young 0x... (x64_addr=0x..., in_used=..., last_used_tick=..., current_age=..., min_age_required=...)")
        return 1

    analyze_events(events)

    if args.timeline:
        timeline_analysis(events, args.window)

    if args.csv:
        export_csv(events, args.csv)

    return 0

if __name__ == '__main__':
    sys.exit(main())
